# Generated by Django 3.2.6 on 2023-12-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('role', models.CharField(blank=True, choices=[('member', 'member'), ('moderator', 'moderator')], default='member', max_length=9, null=True, verbose_name='Роль')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
